### ISSUE TITLE
How do I fill in the loss of a hyperparam causing divergence?

### ISSUE THREAD

**Issue by cuihenggang** [JasperSnoek/spearmint#57]
Hello,

I'm using spearmint-lite to search for a good step size and regularization term for my machine learning application. If I understand correctly, I should fill in the training loss (if I'm not interested in the validation loss) in the result.dat file after running with each set of step size and regularization term. 

However, I find sometimes my application diverges (with nan or inf loss) with the step size and regularization term proposed by Spearmint, and Spearmint does not accept nan or inf values as the result. So in that case, how do I tell Spearmint that this set of step size and regularization term leads to divergence?

Thank you!
Cui

**Comment by JasperSnoek** [comment]
You should mark those as "constraint violations" (take a look at this paper
for details: http://arxiv.org/abs/1403.5607).  This is implemented in
GPConstrainedEIChooser.py
https://github.com/JasperSnoek/spearmint/blob/master/spearmint/spearmint/chooser/GPConstrainedEIChooser.py

Hope that helps!

**Comment by cuihenggang** [comment]
Hi,

Thank you for pointing out the constrained chooser. I am now using the GPConstrainedEIChooser. However, I get the following exception. What could be wrong?

Traceback (most recent call last):
  File "spearmint/spearmint-lite/spearmint-lite.py", line 219, in <module>
    main()
  File "spearmint/spearmint-lite/spearmint-lite.py", line 84, in main
    main_controller(options, args)
  File "spearmint/spearmint-lite/spearmint-lite.py", line 190, in main_controller
    np.nonzero(grid_idx == 0)[0])
  File "/usr/local/lib/python2.7/dist-packages/chooser/GPConstrainedEIChooser.py", line 240, in next
    durations[complete])
  File "/usr/local/lib/python2.7/dist-packages/chooser/GPConstrainedEIChooser.py", line 161, in _real_init
    self.constraint_gain  = state['constraint_gain']
KeyError: 'constraint_gain'

Thank you very much!

Cui

**Comment by cuihenggang** [comment]
I find the 'constraint_gain' is not dumped to the state file:

https://github.com/JasperSnoek/spearmint/blob/b37a541be1ea035f82c7c82bbd93f5b4320e7d91/spearmint/spearmint/chooser/GPConstrainedEIChooser.py#L106

Thank you,
Cui
