### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by pswpswpsw** [JasperSnoek/spearmint#73]
Ubuntu 18.04, following the procedure, installing scipy, numpy, google-protobuf from the official site. Install the C++ version and python version both. 

First, when I ./bin/make_protobufs, it turns out the message:
`[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: spearmint.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
`
which I believe it is due to 4 years ago, google proto has only one syntax. So it using proto2 and I tihnk everything should be fine. So I add
`syntax = "proto2";`
In the head of proto file of spearmint. (note that this operation does not matter at all)

However, when I run the 
`./spearmint ../examples/braninpy/config.pb --driver=local --method=GPEIOptChooser --method-args=noiseless=1`
or
`python main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 ../examples/braninpy/config.pb
`
or 
`python spearmint-lite.py braninpy`

it gives me the following error

```
Traceback (most recent call last):
  File "/media/shawnpan/cd43d6f5-cfb6-4652-80ef-ad2fe40c6a10/shaowu/phd/MC_dropout/spearmint/spearmint/bin/../spearmint/main.py", line 43, in <module>
    from ExperimentGrid  import *
  File "/media/shawnpan/cd43d6f5-cfb6-4652-80ef-ad2fe40c6a10/shaowu/phd/MC_dropout/spearmint/spearmint/spearmint/ExperimentGrid.py", line 30, in <module>
    from spearmint_pb2 import *
  File "/media/shawnpan/cd43d6f5-cfb6-4652-80ef-ad2fe40c6a10/shaowu/phd/MC_dropout/spearmint/spearmint/spearmint/spearmint_pb2.py", line 23, in <module>
    serialized_pb=_b('\n\x0fspearmint.proto\"\xcc\x01\n\x03Job\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x10\n\x08\x65xpt_dir\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x1b\n\x08language\x18\x04 \x02(\x0e\x32\t.Language\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x19\n\x05param\x18\x06 \x03(\x0b\x32\n.Parameter\x12\x10\n\x08submit_t\x18\x07 \x01(\x04\x12\x0f\n\x07start_t\x18\x08 \x01(\x04\x12\r\n\x05\x65nd_t\x18\t \x01(\x04\x12\r\n\x05value\x18\n \x01(\x01\x12\x10\n\x08\x64uration\x18\x0b \x01(\x01\"L\n\tParameter\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07int_val\x18\x02 \x03(\x03\x12\x0f\n\x07str_val\x18\x03 \x03(\t\x12\x0f\n\x07\x64\x62l_val\x18\x04 \x03(\x01\"\x91\x02\n\nExperiment\x12\x1b\n\x08language\x18\x01 \x02(\x0e\x32\t.Language\x12\x0c\n\x04name\x18\x02 \x02(\t\x12+\n\x08variable\x18\x03 \x03(\x0b\x32\x19.Experiment.ParameterSpec\x1a\xaa\x01\n\rParameterSpec\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04size\x18\x02 \x02(\r\x12,\n\x04type\x18\x03 \x02(\x0e\x32\x1e.Experiment.ParameterSpec.Type\x12\x0f\n\x07options\x18\x04 \x03(\t\x12\x0b\n\x03min\x18\x05 \x01(\x01\x12\x0b\n\x03max\x18\x06 \x01(\x01\"$\n\x04Type\x12\x07\n\x03INT\x10\x01\x12\t\n\x05\x46LOAT\x10\x02\x12\x08\n\x04\x45NUM\x10\x03*A\n\x08Language\x12\n\n\x06MATLAB\x10\x01\x12\n\n\x06PYTHON\x10\x02\x12\t\n\x05SHELL\x10\x03\x12\x07\n\x03MCR\x10\x04\x12\t\n\x05TORCH\x10\x05')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

**Comment by pswpswpsw** [comment]
Solved:

I changed to HIPS Spearmint

The issue is mainly due to google protobuf generate the file with additional `pb2` name so that there is something weird going on. Using HIPS everything works out fine.
